.RC $Header: /nfs/medea/u0/rel5/rcs/Tools/cmusnmp/apps/snmpget.1,v 1.2 1992/07/29 18:16:51 djw Exp $
.\* /***********************************************************
.\" 	Copyright 1988, 1989 by Carnegie Mellon University
.\" 
.\"                       All Rights Reserved
.\" 
.\" Permission to use, copy, modify, and distribute this software and its 
.\" documentation for any purpose and without fee is hereby granted, 
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in 
.\" supporting documentation, and that the name of CMU not be
.\" used in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.  
.\" 
.\" CMU DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
.\" ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
.\" CMU BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
.\" ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
.\" SOFTWARE.
.\" ******************************************************************/
.TH SNMPGET 1 "17 September 1989"
.UC 4
.SH NAME
snmpget - communicates with a network entity using SNMP GET Requests.
.SH SYNOPSIS
snmpget host community variable-name [variable-name]...
.SH DESCRIPTION
Snmpget is an SNMP application that uses the GET Request to query for
information on a network entity.  One or more fully qualified object
identifiers may be given as arguments on the command line.
Each variable name is given in the format specified in
.IR variables (5).
.PP
The
.I host
specification may be either a host name or an internet address
specified in "dot notation"
.PP
The
.I community
specifies the community name for the transaction with the remote system.
.PP
For example
.PP
.I snmpget netdev-kbox.cc.cmu.edu public system.sysdescr.0 system.sysUpTime.0
.PP
will retrieve the variables sysDescr.0 and sysUpTime.0:
.PP
.I Name: system.sysDescr.0
.br
.I OCTET STRING- (ascii):	Kinetics FastPath2
.PP
.I Name: system.sysUpTime.0
.br
.I Timeticks: (2270351) 6:18:23
.PP
If the network entity has an error processing the request packet, an error
packet will be returned and a message will be shown, helping to pinpoint in what
way the request was malformed.  If there were other variables in the request,
the request will be resent without the bad variable.
.PP
Adding a "-d" to the argument list will cause the application to dump input and output packets.
.PP
.SH "SEE ALSO"
variables(5), RFC 1065, RFC 1212, RFC 1213

